server:
  port: 8000
spring:
  main:
    web-application-type: REACTIVE
  application:
    name: msvc-api-gateway
  kafka:
    bootstrapServers: localhost:9092
  logging:
    level:
      org.springframework.cloud.gateway: TRACE
      reactor.netty.http.client: TRACE
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: lb://msvc-catalog
          predicates:
            - Path=catalog/**
          filters:
           - PrefixPath=/api/v1/
        - id: notifications
          uri: lb://msvc-notifications
          predicates:
            - Path=notifications/**
          filters:
           - PrefixPath=/api/v1/
        - id: orders
          uri: lb://msvc-orders
          predicates:
            - Path=orders/**
          filters:
           - PrefixPath=/api/v1/
        - id: payments
          uri: lb://msvc-payments
          predicates:
            - Path=payments/**
          filters:
           - PrefixPath=/api/v1/
        - id: shopping-cart
          uri: lb://msvc-shopping-cart
          predicates:
            - Path=shopping-cart/**
          filters:
           - PrefixPath=/api/v1/
        - id: auth
          uri: lb://msvc-auth
          predicates:
            - Path=auth/**
          filters:
           - PrefixPath=/api/v1/
