server:
  port: 8060
spring:
  application:
    name: msvc-auth
  jwt:
    expiration: 604800000
    secret: "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-dawn-tree-a4nn2ysx-pooler.us-east-1.aws.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_tzL3yU8HnjED
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
