server:
  port: 8070
spring:
  application:
    name: msvc-reviews
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: eureka-microservice
  client:
    service-url:
      defaultZone: http://eureka-microservice:8761/eureka/
