server:
  port: 8040
spring:
  application:
    name: msvc-payments
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ecommerce-db:5432/ecommerce
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: eureka-microservice
  client:
    service-url:
      defaultZone: http://eureka-microservice:8761/eureka/
stripe:
 key:
  secret: sk_test_51Nv41pHdRJMRyS5QZ8X4RijGsHGAzBGNjuXhF381a0HXhPWdPkeNjm3ph46yBZtajsCd20Ki5WKAKoGUWjtjSTv200JPunuGbY
