server:
  port: 8040
spring:
  application:
    name: msvc-payments

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
