server:
  port: 8000
spring:
  application:
    name: msvc-api-gateway
  kafka:
    bootstrapServers: localhost:9092
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: http://localhost:8010
          predicates:
            - Path=/api/catalog/test
        - id: notifications
          uri: http://localhost:8020
          predicates:
            - Path=/api/notifications/**
        - id: orders
          uri: http://localhost:8030
          predicates:
            - Path=/api/orders/**
        - id: payments
          uri: http://localhost:8040
          predicates:
            - Path=/api/payments/**
        - id: shopping-cart
          uri: http://localhost:8050
          predicates:
            - Path=/api/shopping-cart/**
        - id: login
          uri: http://localhost:8060
          predicates:
            - Path=/api/auth/login
        - id: register
          uri: http://localhost:8060
          predicates:
            - Path=/api/auth/register
        - id: validate
          uri: http://localhost:8060
          predicates:
            - Path=/api/auth/validate
