server:
  port: 8000
spring:
  application:
    name: msvc-api-gateway
  kafka:
    bootstrapServers: localhost:9092
  logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: TRACE
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: lb://msvc-auth
          predicates:
            - Path=/api/catalog/test
        - id: notifications
          uri: lb://msvc-notifications
          predicates:
            - Path=/api/notifications/**
        - id: orders
          uri: lb://msvc-orders
          predicates:
            - Path=/api/orders/**
        - id: payments
          uri: lb://msvc-payments
          predicates:
            - Path=/api/payments/**
        - id: shopping-cart
          uri: lb://msvc-shopping-cart
          predicates:
            - Path=/api/shopping-cart/**
        - id: login
          uri: lb://msvc-auth
          predicates:
            - Path=/api/auth/login
        - id: register
          uri: lb://msvc-auth
          predicates:
            - Path=/api/auth/register
