server:
  port: 8010
spring:
  application:
    name: msvc-catalog
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-dawn-tree-a4nn2ysx.us-east-1.aws.neon.tech/neondb
    username: neondb_owner
    password: npg_qmyP7jREw4kZ
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  instance:
    hostname: eureka-microservice
  client:
    service-url:
      defaultZone: http://eureka-microservice:8761/eureka/
