server:
  port: 8000
spring:
  application:
    name: msvc-api-gateway
  jwt:
    expiration: 604800000
    secret: "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
            maxAge: 3600
     
      routes:
        - id: auth
          uri: lb://msvc-auth
          predicates:
            - Path=/api/v1/auth/**
        - id: catalog
          uri: lb://msvc-catalog
          predicates:
          - Path=/api/v1/catalog/**
        - id: reviews
          uri: lb://msvc-reviews
          predicates:
          - Path=/api/v1/reviews/**
        - id: shopping-cart
          uri: lb://msvc-shopping-cart
          predicates:
          - Path=/api/v1/shopping-cart/**
        - id: payments
          uri: lb://msvc-payments
          predicates:
          - Path=/api/v1/payments/**
          
eureka:
  instance:
    hostname: eureka-microservice
  client:
    service-url:
      defaultZone: http://eureka-microservice:8761/eureka/
