server:
  port: 8000
spring:
  main:
    web-application-type: REACTIVE
  application:
    name: msvc-api-gateway
  kafka:
    bootstrapServers: localhost:9092
  logging:
    level:
      org.springframework.cloud.gateway: TRACE
      reactor.netty.http.client: TRACE
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: lb://msvc-catalog
          predicates:
            - Path=/api/catalog/**
        - id: notifications
          uri: lb://msvc-notifications
          predicates:
            - Path=/api/notifications/**
        - id: orders
          uri: lb://msvc-orders
          predicates:
            - Path=/api/orders/**
        - id: payments
          uri: lb://msvc-payments
          predicates:
            - Path=/api/payments/**
        - id: shopping-cart
          uri: lb://msvc-shopping-cart
          predicates:
            - Path=/api/shopping-cart/**
        - id: auth
          uri: lb://msvc-auth
          predicates:
            - Path=/api/auth/**

  management:
    endpoints:
      web:
        exposure:
          include: 'gateway'
