server:
  port: 8000
spring:
  main:
    web-application-type: REACTIVE
  application:
    name: msvc-api-gateway
  kafka:
    bootstrapServers: localhost:9092
  logging:
    level:
      org.springframework.cloud.gateway: TRACE
      reactor.netty.http.client: TRACE
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: lb://msvc-catalog
          predicates:
            - Path=/api/v1/catalog/**
          filters:
            - RewritePath=/api/v1/catalog/(?<segment>.*), /catalog/\${segment}
        - id: notifications
          uri: lb://msvc-notifications
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - PrefixPath=/api/v1
        - id: orders
          uri: lb://msvc-orders
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - PrefixPath=/api/v1
        - id: payments
          uri: lb://msvc-payments
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - PrefixPath=/api/v1
        - id: shopping-cart
          uri: lb://msvc-shopping-cart
          predicates:
            - Path=/api/v1/shopping-cart/**
          filters:
            - PrefixPath=/api/v1
        - id: auth
          uri: lb://msvc-auth
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - PrefixPath=/api/v1
