server:
  port: 8000
spring:
  application:
    name: msvc-api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
            maxAge: 3600
     
      routes:
        - id: auth
          uri: lb://msvc-auth
          predicates:
            - Path=/api/v1/auth/**
        - id: catalog
          uri: lb://msvc-catalog
          predicates:
          - Path=/api/v1/catalog/**
        - id: reviews
          uri: lb://msvc-reviews
          predicates:
          - Path=/api/v1/reviews/**
        - id: shopping-cart
          uri: lb://msvc-shopping-cart
          predicates:
          - Path=/api/v1/shopping-cart/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
