server:
  port: 8000
spring:
  application:
    name: msvc-api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://msvc-auth
          predicates:
            - Path=/api/v1/auth/**
