server:
  port: 8050
spring:
  application:
    name: msvc-shopping-cart
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-dawn-tree-a4nn2ysx.us-east-1.aws.neon.tech/neondb
    username: neondb_owner
    password: npg_qmyP7jREw4kZ
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: https://e-commerce-backend-eureka.onrender.com/eureka/
